from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


_HIGH_RISK_VALIDATION_RULES: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "It can delete or irreversibly replace files or repository state.",
        re.compile(
            r"(?i)(?:"
            r"\b(?:rm|rmdir|del|erase)\b|remove-item\b|shutil\.rmtree\b|"
            r"(?:\.unlink|os\.remove|os\.rmdir)\s*\(|"
            r"\bgit\s+(?:clean\b|reset\s+--hard\b|checkout\s+--\b|restore\b)"
            r")"
        ),
    ),
    (
        "It can create or change files while it runs.",
        re.compile(
            r"(?i)(?:"
            r"\b(?:set-content|add-content|out-file|copy-item|move-item|new-item|mkdir|touch)\b|"
            r"\.write_(?:text|bytes)\s*\(|\bwriteall(?:text|bytes)\s*\(|"
            r"\bgit\s+(?:add|commit|merge|rebase|cherry-pick|stash|switch|checkout)\b"
            r")"
        ),
    ),
    (
        "It can install or update software on this computer.",
        re.compile(
            r"(?i)(?:"
            r"\b(?:python\s+-m\s+)?pip\s+install\b|"
            r"\b(?:npm|pnpm|yarn)\s+(?:install|add|update|upgrade)\b|"
            r"\b(?:winget|choco|apt(?:-get)?|dnf|yum|brew)\s+(?:install|upgrade|update)\b"
            r")"
        ),
    ),
    (
        "It can request administrator access or change host services or settings.",
        re.compile(
            r"(?i)(?:"
            r"\bsudo\b|\brunas\b|start-process\b[^\r\n]*-verb\s+runas\b|"
            r"\b(?:systemctl|service)\s+(?:start|stop|restart|enable|disable)\b|"
            r"\b(?:start-service|stop-service|restart-service|set-service)\b|"
            r"\breg(?:\.exe)?\s+(?:add|delete|import|restore)\b|\bsetx\b|"
            r"\b(?:taskkill|stop-process|kill)\b"
            r")"
        ),
    ),
    (
        "It can start, stop, rebuild, or alter containers or infrastructure.",
        re.compile(
            r"(?i)(?:"
            r"\bdocker(?:\s+compose)?\s+(?:up|down|restart|build|pull|push|run|exec|rm|rmi)\b|"
            r"\bkubectl\s+(?:apply|create|delete|edit|exec|patch|replace|rollout|scale|set)\b|"
            r"\bterraform\s+(?:apply|destroy|import|taint)\b|"
            r"\bpulumi\s+(?:up|destroy|import)\b|\bansible-playbook\b"
            r")"
        ),
    ),
    (
        "It can publish, deploy, upload, or change an external system.",
        re.compile(
            r"(?i)(?:"
            r"\bgit\s+push\b|\bgh\s+pr\s+merge\b|"
            r"\b(?:npm\s+publish|twine\s+upload|docker\s+push)\b|"
            r"\b(?:vercel|netlify|flyctl)\s+(?:deploy|publish)\b|"
            r"\b(?:alembic\s+upgrade|prisma\s+migrate\s+deploy|flyway\s+migrate)\b|"
            r"\b(?:requests|httpx)\.(?:post|put|patch|delete)\s*\(|"
            r"\bcurl(?:\.exe)?\b[^\r\n]*(?:(?:--request|-x)\s*(?:post|put|patch|delete)\b|"
            r"--data(?:-binary|-raw)?\b|\s-d\s|--upload-file\b)|"
            r"\binvoke-(?:restmethod|webrequest)\b[^\r\n]*(?:"
            r"-method\s+(?:post|put|patch|delete)\b|-body\b|-infile\b)"
            r")"
        ),
    ),
)


def validation_command_approval(command: str) -> dict[str, Any]:
    """Classify only clear, consequential validation side effects.

    Validation commands are registered by the project owner rather than
    generated by a provider. Routine tests, linters, compilers, read-only
    assertions, and smoke reads therefore run without an operator ceremony.
    Approval is reserved for commands whose text clearly advertises effects
    beyond inspecting the isolated worktree.
    """

    reasons = [message for message, pattern in _HIGH_RISK_VALIDATION_RULES if pattern.search(command)]
    return {
        "required": bool(reasons),
        "risk": "high" if reasons else "routine",
        "summary": (
            "This check can affect more than the isolated working copy."
            if reasons
            else "Routine project check; no operator approval is needed."
        ),
        "reasons": reasons,
    }


@dataclass(frozen=True)
class ValidationDefinition:
    id: str
    command: str
    environment: str
    required: bool = True

    def approval(self, enabled: bool = True) -> dict[str, Any]:
        value = validation_command_approval(self.command)
        return {**value, "required": bool(enabled and value["required"])}


@dataclass(frozen=True)
class ProjectDefinition:
    id: str
    root: Path
    read_only: bool
    instruction_files: tuple[str, ...]
    validations: tuple[ValidationDefinition, ...]
    implementation_enabled: bool = False
    write_allowlist: tuple[str, ...] = ()
    commit_on_accept: bool = True
    allow_no_validations: bool = False
    validation_requires_approval: bool = True
    evidence_exclude_paths: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        for item in self.instruction_files + self.write_allowlist + self.evidence_exclude_paths:
            relative = Path(item)
            target = (self.root / relative).resolve()
            if relative.is_absolute() or (target != self.root and self.root not in target.parents):
                raise ValueError(f"project path escapes root: {item}")
        if any(not item.strip() or item.replace("\\", "/").strip("/") in {"", "."} for item in self.evidence_exclude_paths):
            raise ValueError("evidence exclude paths must name a repository subpath")
        validation_ids: set[str] = set()
        for validation in self.validations:
            if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,63}", validation.id):
                raise ValueError(f"invalid validation id: {validation.id}")
            if validation.id in validation_ids:
                raise ValueError(f"duplicate validation id: {validation.id}")
            validation_ids.add(validation.id)
            if not validation.command.strip():
                raise ValueError(f"validation command cannot be empty: {validation.id}")
        if (
            self.implementation_enabled
            and not self.allow_no_validations
            and not any(
                item.required and item.environment in {"local", "either"}
                for item in self.validations
            )
        ):
            raise ValueError("implementation-enabled projects require a required local validation or explicit allow_no_validations")

    @classmethod
    def from_file(cls, path: Path) -> "ProjectDefinition":
        return cls.from_value(json.loads(path.read_text(encoding="utf-8")))

    @classmethod
    def from_value(cls, value: dict[str, Any]) -> "ProjectDefinition":
        root = Path(str(value["root"])).expanduser().resolve()
        validations = tuple(
            ValidationDefinition(
                str(item["id"]),
                str(item["command"]),
                str(item["environment"]),
                bool(item.get("required", True)),
            )
            for item in value.get("validations", [])
        )
        if not value.get("read_only"):
            raise ValueError("M1 project definitions must be read-only")
        if any(item.environment not in {"local", "vps", "either"} for item in validations):
            raise ValueError("project validation environment must be local, vps, or either")
        implementation = value.get("implementation", {})
        implementation_enabled = bool(implementation.get("enabled", False))
        write_allowlist = tuple(str(item) for item in implementation.get("write_allowlist", []))
        evidence_exclude_paths = tuple(str(item) for item in implementation.get("evidence_exclude_paths", []))
        if implementation_enabled and not write_allowlist:
            raise ValueError("implementation-enabled projects require a write allowlist")
        return cls(
            id=str(value["id"]),
            root=root,
            read_only=True,
            instruction_files=tuple(str(item) for item in value.get("instruction_files", [])),
            validations=validations,
            implementation_enabled=implementation_enabled,
            write_allowlist=write_allowlist,
            commit_on_accept=bool(implementation.get("commit_on_accept", True)),
            allow_no_validations=bool(implementation.get("allow_no_validations", False)),
            validation_requires_approval=bool(implementation.get("validation_requires_approval", True)),
            evidence_exclude_paths=evidence_exclude_paths,
        )

    def snapshot(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "root": str(self.root),
            "read_only": self.read_only,
            "instruction_files": list(self.instruction_files),
            "validations": [
                {
                    "id": item.id,
                    "command": item.command,
                    "environment": item.environment,
                    "required": item.required,
                }
                for item in self.validations
            ],
            "implementation": {
                "enabled": self.implementation_enabled,
                "write_allowlist": list(self.write_allowlist),
                "commit_on_accept": self.commit_on_accept,
                "allow_no_validations": self.allow_no_validations,
                "validation_requires_approval": self.validation_requires_approval,
                "evidence_exclude_paths": list(self.evidence_exclude_paths),
            },
        }

    def revision(self) -> str:
        result = subprocess.run(
            ["git", "-C", str(self.root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=15,
        )
        if result.returncode != 0:
            raise ValueError(f"project revision lookup failed: {result.stderr.strip()}")
        return result.stdout.strip()

    def git_context(self) -> tuple[str | None, bool | None, str | None]:
        branch = subprocess.run(
            ["git", "-C", str(self.root), "branch", "--show-current"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=15,
        )
        # Untracked files never travel into the isolated execution worktree and
        # the accepted commit lands on the run branch, so only tracked
        # modifications make the source checkout untrustworthy as a baseline.
        #
        # This is a background/read-only status probe. Prevent Git's optional
        # index refresh so the relay neither takes nor collides with an index
        # lock while an editor, agent, or another Git process is active.
        status = subprocess.run(
            [
                "git",
                "--no-optional-locks",
                "-C",
                str(self.root),
                "status",
                "--porcelain",
                "--untracked-files=no",
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=15,
        )
        branch_name = branch.stdout.strip() or None if branch.returncode == 0 else None
        if status.returncode != 0:
            detail = status.stderr.strip() or status.stdout.strip() or f"git exited with status {status.returncode}"
            return branch_name, None, f"git status failed: {detail}"
        return (
            branch_name,
            bool(status.stdout),
            None,
        )

    def check(self) -> dict[str, Any]:
        instruction_status = {item: (self.root / item).resolve().is_file() for item in self.instruction_files}
        try:
            revision = self.revision()
        except ValueError as error:
            revision = None
            error_text = str(error)
        else:
            error_text = None
        ready = self.root.is_dir() and revision is not None and all(instruction_status.values())
        branch, dirty, source_checkout_error = (
            self.git_context()
            if self.root.is_dir()
            else (None, None, "project root is not a directory")
        )
        implementation_ready = ready and (not self.implementation_enabled or dirty is False)
        return {
            "id": self.id,
            "root": str(self.root),
            "read_only": self.read_only,
            "implementation_enabled": self.implementation_enabled,
            "write_allowlist": list(self.write_allowlist),
            "commit_on_accept": self.commit_on_accept,
            "allow_no_validations": self.allow_no_validations,
            "validation_requires_approval": self.validation_requires_approval,
            "evidence_exclude_paths": list(self.evidence_exclude_paths),
            "validations": [
                {
                    "id": item.id,
                    "command": item.command,
                    "environment": item.environment,
                    "required": item.required,
                }
                for item in self.validations
            ],
            "source_revision": revision,
            "branch": branch,
            "dirty": dirty,
            "source_checkout_error": source_checkout_error,
            "implementation_ready": implementation_ready,
            "implementation_error": (
                "source checkout must be clean" if self.implementation_enabled and dirty else
                (
                    source_checkout_error or "source checkout status is unavailable"
                ) if self.implementation_enabled and dirty is None else
                None
            ),
            "instruction_files": instruction_status,
            "ready": ready,
            "error": error_text,
        }


def load_projects(directory: Path | None = None) -> dict[str, ProjectDefinition]:
    root = directory or Path(__file__).with_name("projects")
    projects = {}
    for path in sorted(root.glob("*.json")):
        project = ProjectDefinition.from_file(path)
        if project.id in projects:
            raise ValueError(f"duplicate project definition: {project.id}")
        projects[project.id] = project
    return projects
